export const teamMembers = [
  // 4th years
  {
    name: 'Nischal Vatsa',
    profilePic: '/nishchal.jpeg',
    instagramUrl: 'https://www.instagram.com/nonischaldont/',
    linkedinUrl: 'https://www.linkedin.com/in/nishchal-vatsa-265978242?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    name: 'Ali Yazdan',
    profilePic: '/ali.jpg',
    instagramUrl: 'https://www.instagram.com/zaidiyazda/profilecard/?igsh=MW43d3pwYTJ0cjk1cQ==',
    linkedinUrl: 'https://www.linkedin.com/in/yazdan-ali?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    name: 'Abhinav Pandey',
    profilePic: '/abhinav.jpg',
    instagramUrl: 'https://www.instagram.com/whyabhinav/profilecard/?igsh=MWxocnRmeWh0ejhueQ==',
    linkedinUrl: 'https://www.linkedin.com/in/abhinav-pandey-662231230?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    name: 'Krishna Chandra Roy',
    profilePic: '/krishna.jpg',
    instagramUrl: 'https://instagram.com/__roy__krishna__?igshid=MTgxemgyN2g2dzVv',
    linkedinUrl: 'https://www.linkedin.com/in/krishna-chandra-roy-098467228?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    name: 'Aman Adarsh',
    profilePic: '/aman.jpg',
    instagramUrl: 'https://www.instagram.com/_aman_adarsh_?igsh=MWI0bHhhaDE1YzJ0bg==',
    linkedinUrl: 'https://www.linkedin.com/in/aman-adarsh01',
  },
  {
    name: 'Ayush Raj',
    profilePic: '/AYUSH.jpg',
    instagramUrl: 'https://www.instagram.com/ayyush_raj/profilecard/?igsh=MmJ3OXQ3ZnN4ODNh',
    linkedinUrl: 'www.linkedin.com/in/ayyush-raj',
  },
  {
    name: 'Nikhitha',
    profilePic: '/Nikhitha.jpeg',
    instagramUrl: 'https://instagram.com/teammate2',
    linkedinUrl: 'www.linkedin.com/in/lalithasainikhitha',
  },
  {
    name: 'Tanmay Deshpande',
    profilePic: '/dsp.png',
    instagramUrl: 'https://www.instagram.com/dsp.tanmay/',
    linkedinUrl: 'https://www.linkedin.com/in/tanmay-deshpande-a37994242',
  },
  {
    name: 'Mayank Pandey',
    profilePic: '/mayank.jpg',
    instagramUrl: 'https://www.instagram.com/mykpdy/',
    linkedinUrl: 'https://www.linkedin.com/in/mayank-pandey-1a16b7240/',
  },
  //   3rd years
  {
    name: 'Shivani Yargol',
    profilePic: '/shivani.jpg',
    instagramUrl: 'https://www.instagram.com/shivaniiii_yargol/profilecard/?igsh=N3VjYmdhNDR2YWM1',
    linkedinUrl: 'https://www.linkedin.com/in/shivani-yargol-82539a288?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    name: 'Lavanya Chawda',
    profilePic: '/lavanya.jpg',
    instagramUrl: 'https://www.instagram.com/lavanya_chawda/profilecard/?igsh=MTdocXk0ZTAwZHQyYw==',
    linkedinUrl: 'https://www.linkedin.com/in/lavanya-chawda-61ab88258?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    name: 'Akriti Kumari',
    profilePic: '/akriti.jpg',
    instagramUrl: 'https://www.instagram.com/akriti_.11/profilecard/?igsh=a2lpZHJ1eWZjdHQ2',
    linkedinUrl: 'linkedin.com/in/akriti-kumari-66ba7a263',
  },
  {
    name: 'Adya Jha',
    profilePic: '/adya.jpg',
    instagramUrl: 'https://instagram.com/teammate2',
    linkedinUrl: 'https://linkedin.com/in/teammate2',
  },
  {
    name: 'Aditi',
    profilePic: '/ADITI.jpg',
    instagramUrl: 'https://instagram.com/teammate2',
    linkedinUrl: 'https://linkedin.com/in/teammate2',
  },
  {
    name: 'Raghavi M',
    profilePic: '/raghvi.jpg',
    instagramUrl: 'https://www.instagram.com/raghavi_m_/profilecard/?igsh=cnB2d3d6c2VtMTJy',
    linkedinUrl: 'https://in.linkedin.com/in/raghavi-m-76a645247',
  },
  {
    name: 'Nesara N',
    profilePic: '/nesara.jpg',
    instagramUrl: 'https://www.instagram.com/nesaraa___?igsh=MWhzdThucW1jcGxyeg==',
    linkedinUrl: 'https://linkedin.com/in/teammate2',
  },
  {
    name: 'Tejaswi Sinha',
    profilePic: '/vinayak.jpg',
    instagramUrl: 'https://www.instagram.com/sinha.vinayak55?igsh=ZWR3Z2hpdmllYWpo',
    linkedinUrl: 'https://www.linkedin.com/in/tejaswi-sinha-935701267?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    name: 'Proneil',
    profilePic: '/proniel.jpeg',
    instagramUrl: 'https://instagram.com/teammate2',
    linkedinUrl: 'https://linkedin.com/in/teammate2',
  },
 
  {
    name: 'Mudit',
    profilePic: '/mudit.jpg',
    instagramUrl: 'https://www.instagram.com/muditshekhar_17/profilecard/?igsh=MWh5OXNmaHc2OTcwYQ==',
    linkedinUrl: 'https://www.linkedin.com/in/mudit-shekhar-339465331',
  },
  {
    name: 'Surya Prakash',
    profilePic: '/surya.jpg',
    instagramUrl: 'https://www.instagram.com/sur_ya_28/profilecard/?igsh=MWUzZHo3cHd1OGkyNg==',
    linkedinUrl: 'https://www.linkedin.com/in/surya-prakash-sah-95749626b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  //   2nd years
  {
    name: 'Aviral Sharma',
    profilePic: '/img10(1).jpg',
    instagramUrl: 'https://www.instagram.com/i_aviralsharma?igsh=MTR1eHNqdW8ycXdoYQ==',
    linkedinUrl: 'https://www.linkedin.com/in/aviral-sharma-4642b4282?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    name: 'Siri Gowri Dinesh',
    profilePic: '/siri.jpeg',
    instagramUrl: 'https://www.instagram.com/sirigowrii.gd/profilecard/?igsh=ODM3cGo2MjJ5emo0',
    linkedinUrl: 'https://linkedin.com/in/teammate2',
  },
  {
    name: 'Parth Dhunde',
    profilePic: '/parth.jpg',
    instagramUrl: 'https://www.instagram.com/pawwriiii/profilecard/?igsh=ODh3bHBqZWlkamg4',
    linkedinUrl: 'https://www.linkedin.com/in/parth-d-a6a0712a3?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    name: 'Akash',
    profilePic: '/akash.jpeg',
    instagramUrl: 'https://www.instagram.com/akashpsh?igsh=MTlqaHlkc3poZHBlcA==',
    linkedinUrl: 'https://linkedin.com/in/teammate2',
  },
  {
    name: 'Aradhya Langer',
    profilePic: '/aradhya.jpeg',
    instagramUrl: 'https://www.instagram.com/aradhya_langer/profilecard/?igsh=YWw5cHp0Z2tneGNw',
    linkedinUrl: 'https://www.linkedin.com/in/aradhya-langer-7b2652274?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    name: 'Amritanshu Shandilya',
    profilePic: '/amrit.jpg',
    instagramUrl: 'https://www.instagram.com/amrit._.shan._.06/profilecard/?igsh=Y3FhNWtneDkwNHR1',
    linkedinUrl: 'https://www.linkedin.com/in/amritanshu-shandilya',
  },
  {
    name: 'Likhita B',
    profilePic: '/likhita.jpeg',
    instagramUrl: 'https://instagram.com/teammate2',
    linkedinUrl: 'https://linkedin.com/in/teammate2',
  },
  {
    name: 'Abhigyan Ojha',
    profilePic: '/abhigyan.jpg',
    instagramUrl: 'https://www.instagram.com/abhigyan._7?igsh=c3l4MjR2ajh4YWdl',
    linkedinUrl: 'https://www.linkedin.com/in/abhigyan-ojha-a39a75331?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    name: 'Harshit',
    profilePic: '/harshit.jpeg',
    instagramUrl: 'https://www.instagram.com/harshittt02_?igsh=bTRqazZpcjhwN2Qw&utm_source=qr',
    linkedinUrl: 'https://www.linkedin.com/in/harshit-kumar-9716102b9?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app',
  },
  {
    name: 'Sudipto Soren',
    profilePic: '/sudipto.jpg',
    instagramUrl: 'https://www.instagram.com/sudipto3636/profilecard/?igsh=eXJnemtkNmF6ZnY5',
    linkedinUrl: 'https://www.linkedin.com/in/sudipto-soren-28260a292',
  },
  {
    name: 'Shabd Swaroop',
    profilePic: '/shabd.jpg',
    instagramUrl: 'https://www.instagram.com/swaroop.here/profilecard/?igsh=bnZhb3o3eHljM3Ew',
    linkedinUrl: 'https://www.linkedin.com/in/shabd-swaroop-a8a184292?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    name: 'Sneha K',
    profilePic: '/sneha.jpg',
    instagramUrl: 'https://www.instagram.com/_sne_0/profilecard/?igsh=YmQ5ODE1ZWZ2bTA5',
    linkedinUrl: 'www.linkedin.com/in/sneha-k-4517402a1',
  },
  {
    name: 'Vidya',
    profilePic: '/vidya0.jpg',
    instagramUrl: 'https://www.instagram.com/vidya__gurram/profilecard/?igsh=MTVwcm9vaWdtbjdodg==',
    linkedinUrl: 'https://linkedin.com/in/teammate2',
  },
  {
    name: 'Kata Mounika',
    profilePic: '/mounika.jpg',
    instagramUrl: 'https://instagram.com/teammate2',
    linkedinUrl: 'https://linkedin.com/in/teammate2',
  },
  {
    name: 'Chiranth',
    profilePic: '/chiranth.jpg',
    instagramUrl: 'https://www.instagram.com/chiranth___2005/profilecard/?igsh=cHF4YTJvbHRhM3Fl',
    linkedinUrl: 'https://linkedin.com/in/teammate2',
  },
  {
    name: 'Shanmukh',
    profilePic: '/shanmukh.jpg',
    instagramUrl: 'https://www.instagram.com/shanmukh_adv/profilecard/?igsh=MTZ1YTVsNjllODY3bQ==',
    linkedinUrl: 'https://www.linkedin.com/in/shanmukh-d-adavi-1a8464288',
  },
  {
    name: 'Sandeep Karam',
    profilePic: '/sandy.jpg',
    instagramUrl: 'https://www.instagram.com/sandeepkaram00?igsh=MW5zdm1qMDdlency&utm_source=qr',
    linkedinUrl: 'https://www.linkedin.com/in/sandeep-karam-2bab232b6/',
  },
  {
    name: 'Yuvraj Singh',
    profilePic: '/yuvi.jpg',
    instagramUrl: 'https://www.instagram.com/yuvraj__simha/profilecard/?igsh=NHp0ZGFyazNvMA==',
    linkedinUrl: 'https://www.linkedin.com/in/yuvraj-singh-a29272297?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    name: 'Swathi H T',
    profilePic: '/SWATHI.jpg',
    instagramUrl: 'https://www.instagram.com/_swathiiii.__/profilecard/?igsh=MTFzeW5lNTJkNGk4bA==',
    linkedinUrl: 'https://linkedin.com/in/teammate2',
  },
  {
    name: 'Sachin Kumar Tiwari',
    profilePic: '/SACHIN.webp',
    instagramUrl: 'https://www.instagram.com/sacchii.in/profilecard/?igsh=MWJmOXBqN3puMWZibg==',
    linkedinUrl: 'https://linkedin.com/in/teammate2',
  },

];
